# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f6a87ef8dcb05d5002dbe4c2eff73f2b196f3e7b03f743c0ecce3f1c9fb8e6d5838f9c474721f92286e4da5cf8bb658db3b68012a95dec42864c65eca7d8502

test:
  secret_key_base: 2f2cdf45e0dadd996013ba6e32894bbd372949c51ea7425757c4ef8c94fb904672c6103fa1798fa67010a27558d5c07fda3659342919ecc62bafa6c036c2294d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
